import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.Scanner;


public class Dota {
	
/////////////////////////////////////////////////////////////////////////////////////////////
/*
DO NOT EDIT THIS FILE!!!
WRITE YOUR SOLUTION IN mysolution.java
*/
/////////////////////////////////////////////////////////////////////////////////////////////

	public static final int MAX_N = 25;
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub

		int test_case;
		int T;
		int N;
		int Answer;
		int[] obs = new int[MAX_N*MAX_N];
		int H1row, H1col, H2row, H2col, T1row, T1col, T2row, T2col;
		
		
		
		try {
			System.setIn(new FileInputStream("sample_input.txt"));
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        Scanner sc = new Scanner(System.in);
        
        T = sc.nextInt();
        for(test_case=1; test_case <= T; test_case++) {
        	mySolution ms = new mySolution();
        	
        	N = sc.nextInt();
        	
        	H1row = sc.nextInt();
        	H1col = sc.nextInt();
        	T1row = sc.nextInt();
        	T1col = sc.nextInt();
        	H2row = sc.nextInt();
        	H2col = sc.nextInt();
        	T2row = sc.nextInt();
        	T2col = sc.nextInt();
        	
        	obs = new int[MAX_N*MAX_N];
        	
        	for (int i = 0; i < N*N; i++) {
    			obs[i] = sc.nextInt();
    		}
    		for (int i = N*N; i < MAX_N * MAX_N; i++) {
    			obs[i] = 0;
    		}
        	
    		Answer = ms.mysolution(N, H1row, H1col, H2row, H2col, T1row, T1col, T2row, T2col, obs);
    		
    		System.out.println("#"+test_case+" "+Answer);
        }
        
        sc.close();
	}

}
